name: 🧪 End-to-end tests
description: 'Reusable workflow to run e2e tests'

inputs:
  url:
    required: false
    description: 'The URL to run the tests against. Default localhost'

runs:
  using: 'composite'
  steps:
    - name: ⬇️ Checkout repo
      uses: actions/checkout@v4

    - name: 📥 Install dependencies
      shell: 'bash'
      run: npm ci

    - name: 💾 Turbo cache
      id: turbo-cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules/.cache/turbo
          **/.turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - name: 📄 Get installed Playwright version
      shell: 'bash'
      run: echo "PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright -m 1 | sed 's/.*@//')"  >> $GITHUB_ENV

    - name: 💾 Cache Playwright binaries
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

    - name: 💽 Install Playwright Browsers (all)
      shell: 'bash'
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium

    - name: 💽 Install Playwright (only system deps)
      shell: 'bash'
      if: steps.playwright-cache.outputs.cache-hit == 'true'
      run: npx playwright install-deps chromium

    - name: 🍄 Run Playwright tests (if tests exist)
      shell: 'bash'
      run: |
        if [ -d "e2e" ] && ls e2e/*.spec.ts 1> /dev/null 2>&1; then
          URL=${{ inputs.url }} npx playwright test e2e/
        else
          echo "⚠️ No Playwright tests found, skipping."
        fi
