import Sidebar from "@/core/component/Sidebar";
import "@/core/styles/globals.css";

import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "E Commerce Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-full h-full flex">
          <div className="min-w-[280px] h-svh max-w-full bg-blue-700 py-[30px] ">
            <Sidebar />
          </div>
          <main className="w-full h-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
