import Sidebar from '@/core/components/Sidebar';
import '@/core/styles/globals.css';

import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'E Commerce Management',
  description: 'Generated by create next app'
};

export default function App({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="grid h-full w-full grid-cols-[280px_auto]">
          <div className="h-full min-h-svh max-w-full min-w-[280px] bg-blue-700 py-[30px]">
            <Sidebar />
          </div>
          <main className="flex h-full w-full flex-col overflow-hidden">{children}</main>
        </div>
      </body>
    </html>
  );
}
